### ISSUE TITLE
Got Non successful exit code trying to follows the example in Readme

### ISSUE THREAD

**Issue by Hiyorimi** [anomaly-guard/nft-deployer#3]
Got 
```python3 deploy-wallet.py                                                                           15.10.22 
using existing key defined in config ...
Traceback (most recent call last):
  File "nft-deployer/deploy-wallet.py", line 10, in <module>
    state = App.lite_client.state(addr)
  File "nft-deployer/pyfift/base/lite_client.py", line 32, in state
    out, _ = self.run(self.config, f"getaccount {address}")
  File "nft-deployer/pyfift/base/lite_client.py", line 81, in run
    raise RuntimeError("Non successful exit code")
RuntimeError: Non successful exit code
```

Once I tried following the README

**Comment by anomaly-guard** [comment]
It appears that you do not have lite-client on your path, or that python cannot detect it.
I added the error to the exception; would you please update with 'git pull' and recheck?

**Comment by anomaly-guard** [comment]
@Hiyorimi

**Comment by Hiyorimi** [comment]
> @Hiyorimi

I'm quite busy atm, going to ask around for the help from the community!
