### ISSUE TITLE
Got UnicodeDecodeError trying to follows the example in Readme

### ISSUE THREAD

**Issue by LevZed** [anomaly-guard/nft-deployer#4]
```bash
> py deploy-wallet.py
no key is provided generating key...
private key: 8A0549DCFAECA60B8C2EC980172D814CCDAEF9E5CAE3B6FBC7885D7BB177ADBB
please save your private key for later access, ideally in config.json
Traceback (most recent call last):
  File "C:\...\nft-deployer\deploy-wallet.py", line 5, in <module>
    App.init()
  File "C:\...\nft-deployer\pyfift\base\app.py", line 24, in init
    cls.key = KeyPair(hex_key)
  File "C:\...\nft-deployer\pyfift\base\keypair.py", line 23, in __init__
    self.pub_key = self._deriv_pub()
  File "C:\...\nft-deployer\pyfift\base\keypair.py", line 29, in _deriv_pub
    outs = Fift().run(self.deriv_pub_key, {
  File "C:\...\nft-deployer\pyfift\base\fift.py", line 30, in run
    out, err = out.decode("utf-8"), err.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 7: invalid start byte
```

**Comment by LevZed** [comment]
I'm not really sure what I did, but the error seems to have disappeared 🥴

**Comment by LevZed** [comment]
Hi @anomaly-guard, how can i communicate with you? I have some questions and suggestions. You can write me in tg (revuza)
